---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: aurora
# description will be included in the image's metadata
description: Personalized image of Aurora DX (HWE).

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx-hwe
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: script
    scripts:
      - remove-repos.sh

  - type: rpm-ostree
    repos:
      # Default
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo

      - https://www.scootersoftware.com/files/scootersoftware.repo
    install:
      # Default
      - micro
      - starship
      
      - bcompare
      - firefox
    remove:
      - asusctl
      - asusctl-rog-gui
      - input-remapper
      - kate
      - kate-krunner-plugin
      - kate-libs
      - kate-plugins
      - kwrite
      - sysprof

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        # From https://github.com/ublue-os/aurora/blob/main/aurora_flatpaks/flatpaks
        - org.kde.kcalc
        - org.kde.gwenview
        - org.kde.kontact
        - org.kde.okular
        - org.kde.kweather
        - org.kde.kclock
        - org.fkoehler.KTailctl
        - com.github.tchx84.Flatseal
        - com.ranfdev.DistroShelf
        - io.github.flattool.Warehouse
        - org.fedoraproject.MediaWriter
        - io.missioncenter.MissionCenter
        - io.github.input_leap.input-leap
        - org.kde.skanpage

        # From https://github.com/ublue-os/aurora/blob/main/dx_flatpaks/flatpaks
        - io.podman_desktop.PodmanDesktop
        - me.iepure.devtoolbox
        - sh.loft.devpod

        - com.discordapp.Discord
        - com.protonvpn.www
        - com.ultimaker.cura
        - org.libreoffice.LibreOffice
        - org.videolan.VLC
    user: {} # Also add Flathub user repo, but no user packages

  - type: bling
    install:
      - 1password

  - type: justfiles
    include:
      - setup-git-global-identity.just
      - setup-hostname.just

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

